
DELIMITER $$
CREATE TRIGGER `sync_update_history`
AFTER UPDATE ON `history` FOR EACH ROW
BEGIN
    INSERT INTO `history_bigint` VALUES (
      NEW.`AUTO_ID`,
      NEW.`DEL_ID`,
      NEW.`ROW_ID`,
      NEW.`TARGET`,
      NEW.`IP_ADDRESS`,
      NEW.`RESOURCE_ID`,
      NEW.`NOTES`,
      NEW.`ENTRY_DATE`,
      NEW.`ARCHIVE_FLAG`,
      NEW.`DEL_FLAG`,
      NEW.`CREATE_DATE`,
      NEW.`USER_TIME_ZONE`,
      NEW.`TZ_ID`,
      NEW.`UPDATE_DATE`,
      NEW.`AUTO_UPDATE_DATE`,
      NEW.`AUTO_UPDATE_SRC`
) ON DUPLICATE KEY UPDATE
      `DEL_ID` = VALUES(`DEL_ID`),
      `ROW_ID` = VALUES(`ROW_ID`),
      `TARGET` = VALUES(`TARGET`),
      `IP_ADDRESS` = VALUES(`IP_ADDRESS`),
      `RESOURCE_ID` = VALUES(`RESOURCE_ID`),
      `NOTES` = VALUES(`NOTES`),
      `ENTRY_DATE` = VALUES(`ENTRY_DATE`),
      `ARCHIVE_FLAG` = VALUES(`ARCHIVE_FLAG`),
      `DEL_FLAG` = VALUES(`DEL_FLAG`),
      `CREATE_DATE` = VALUES(`CREATE_DATE`),
      `USER_TIME_ZONE` = VALUES(`USER_TIME_ZONE`),
      `TZ_ID` = VALUES(`TZ_ID`),
      `UPDATE_DATE` = VALUES(`UPDATE_DATE`),
      `AUTO_UPDATE_DATE` = VALUES(`AUTO_UPDATE_DATE`),
      `AUTO_UPDATE_SRC` = VALUES(`AUTO_UPDATE_SRC`)
    ;
END;
$$
DELIMITER ;